---

- hosts: all
  become: true
  ignore_unreachable: true
  gather_facts: true
  tasks:

  - name: install apache & update directory index and add php support for apache
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      update_cache: yes
      state: latest
    
